const smartShala = {
  id: "smart-shala",
  title: "Smart - Shala",
  description: "website to manage schools virtually",
  imageSrc:
    "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083314/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_224754_dlapma.png",
  problem:
    "In modern educational settings, managing classrooms efficiently while ensuring a conducive learning environment is crucial. Traditional methods of classroom management are often manual, time-consuming, and prone to human error, which can disrupt the learning process. Leveraging software-based solutions in classroom management can enhance operational efficiency, ensure safety, and create an engaging learning atmosphere for students. This project aims to develop a smart software solution to streamline classroom operations, improve resource utilization, and enhance the overall learning experience",
  solution:
    "The Smart Classroom Management Software (SCMS) utilizes advanced algorithms, data analytics, and cloud-based technologies to automate various aspects of classroom management.",
  team: [
    "Bhargavi - Full Stack",
    "Manush - Full Stack",
    "Mayur - Front End",
    "Krish - Front End",
    "Aaishwarya - Front End",
    "Siddharth - Front End",
  ],
  tools: ["ReactJS", "MongoDB", "ExpressJS", "NodeJS", "LLM", "Python"],
  github: "https://github.com/Bhargavimachhi/Smart-Shala",

  features: [
    "🚀 4 Portals - Student, Teacher, School, Authority",
    "💻 Data Analytics",
    "🤖 AI generated homework check and report generation",
    "📷 Automatic Attendance",
    "📖 Virtual Homework submission",
    "🧩 Online Tests",
    "🔐 Issue Management",
    "📚 Resource Management",
  ],

  portals: [
    {
      name: "Students Portal",
      images: [
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084038/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_225854_jsjuv9.png",
          designation: "",
          name: "Profile Page",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084042/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_230015_uc2v3y.png",
          designation: "Upload Homework or File and get AI Analysis",
          name: "Homework Analysis",
          quote:
            "AI will analyze the image and generate report according to that",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084041/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_230311_cquqob.png",
          designation: "Ask Doubts to AI Assistant",
          name: "AI ChatBot",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084040/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_225913_ytnvvd.png",
          designation: "Upload Homework on the portal",
          name: "Homework Submission",
          quote: "Teacher can review the homework",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084040/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_230147_hriyei.png",
          designation: "Receive Important Notifications from school",
          name: "Notifications",
          quote: "regarding tests, events, functions, clubs etc.",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084039/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_230132_gc8vh9.png",
          designation: "Access your attendance data",
          name: "Attendance",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745084038/portfolio/website%20images/smart-shala/Student%20Portal/Screenshot_2025-04-19_230049_lhku1t.png",
          designation: "Attempt Quizzes generated by teacher",
          name: "Quizzes",
          quote: "student and teacher can review marks",
        },
      ],
    },
    {
      name: "Teachers Portal",
      images: [
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083536/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225228_ufnwik.png",
          designation: "",
          name: "Profile Page",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083537/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225243_c11fe8.png",
          designation: "View All Classrooms teacher is part of",
          name: "Classroom Listing",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083537/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225301_sjqp85.png",
          designation: "Assign homework to classroom",
          name: "Homework Assignment",
          quote:
            "all the students of classroom will have to submit the homework",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083539/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225444_i2prrn.png",
          designation: "Teacher can request a resource for classroom",
          name: "Request Resource",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083539/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225424_pqbk3e.png",
          designation: "Teacher can generate issue and notify admin",
          name: "Generate Issue",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083538/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225340_byqiai.png",
          designation: "Mark Attendance of students after choosing classroom",
          name: "Mark Attendance",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083540/portfolio/website%20images/smart-shala/Teacher%20Portal/Screenshot_2025-04-19_225359_yk2jai.png",
          designation:
            "view list of students who have less than 75% of attendance",
          name: "View Attendance Report",
          quote: "",
        },
      ],
    },
    {
      name: "Principal Portal",
      images: [
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083315/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_224951_tngrcp.png",
          designation: "View create classroom of school",
          name: "Classrooms Listing",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083315/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_224934_g6v3ik.png",
          designation: "View All teachers of school",
          name: "Teachers Listing",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083315/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_224908_rxzxni.png",
          designation: "iew All students of school",
          name: "Students Listing",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083315/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_225030_gcx0jh.png",
          designation: "View all issues generated by teachers",
          name: "Issues Listing",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083316/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_225055_t5worx.png",
          designation: "Add, Remove, Assign Resources as per availability",
          name: "Resource Management",
          quote: "",
        },
        {
          src: "https://res.cloudinary.com/dwvppu30v/image/upload/v1745083316/portfolio/website%20images/smart-shala/Admi%20Portal/Screenshot_2025-04-19_225008_txzg5c.png",
          designation: "view data analysis of each classroom",
          name: "Data Analytics",
          quote: "",
        },
      ],
    },
  ],
};

export const projectsDetails = {
  "smart-shala": smartShala,
};
